# dict_data.py — dictionnaires intégrés directement dans le code
# (en production, chargez-les depuis vos fichiers JSON)

DICT_NORM = {
  "unicode_arabic": {
    "أ": "ا", "إ": "ا", "آ": "ا", "ٱ": "ا", "ٲ": "ا", "ٳ": "ا",
    "ک": "ك", "گ": "ك", "ڪ": "ك", "ګ": "ك",
    "ڨ": "ق", "ڬ": "ق", "ڥ": "ق",
    "ہ": "ه", "ؠ": "ي", "ۄ": "و", "ۆ": "و", "ۇ": "و", "ں": "ن"
  },
  "arabizi_words": {
    "wach": "واش", "khayba": "خايبة", "bonus": "بونوس",
"puce": "شريحة","zwina": "زينة", "mliha": "مليحة",
    "bezzaf": "بزاف", "bzf": "بزاف", "nul": "نول", "khlas": "خلاص",
    "khlesna": "خلصنا", "walo": "والو", "daba": "دابا", "deba": "دابا",
    "kifech": "كيفاش", "kifach": "كيفاش", "kifash": "كيفاش",
    "haka": "هاكا", "kima": "كيما", "barka": "بركة", "lazem": "لازم",
    "ghir": "غير", "safi": "صافي", "mazal": "مزال", "rana": "رانا",
    "rahi": "راهي", "rani": "راني", "raho": "راهو", "rahom": "راهم",
    "hna": "حنا", "blad": "بلاد", "bladna": "بلادنا",
    "kamel": "كامل", "sahel": "ساهل", "chhal": "شحال", "chhel": "شحال",
    "hadi": "هادي", "hada": "هادا", "khoya": "خويا", "khouya": "خويا",
    "dyal": "ديال", "dial": "ديال", "bhal": "بحال", "sahbi": "صاحبي",
    "wakha": "واخا", "rabi": "ربي", "rabbi": "ربي",
    "khdma": "خدمة", "khedma": "خدمة",
    "flexi": "فليكسي", "flexili": "فليكسي", "nflexi": "فليكسي",
    "nchalh": "إن شاء الله", "nachalh": "إن شاء الله",
    "inchalh": "إن شاء الله", "inshalah": "إن شاء الله",
    "inshalh": "إن شاء الله", "inshaallah": "إن شاء الله",
    "inchalah": "إن شاء الله", "inchallah": "إن شاء الله",
    "inshallah": "إن شاء الله", "nchallah": "إن شاء الله",
    "nshallah": "إن شاء الله",
    "wlh": "والله", "wlhi": "والله", "wellah": "والله",
    "wallah": "والله", "wallahi": "والله",
    "slm": "سلام",
    "nkhles": "نخلص", "jiy": "جي", "t9ouli": "تقولي", "twer": "توير",
    "rouhk": "روحك", "segmou": "سقمو", "diylkom": "ديالكم",
    "wla": "ولا", "9wdou": "قودو", "jiboulna": "جيبولنا",
    "charika": "شركة", "klch": "كلش", "nktona": "نكتونا",
    "rouho": "روحو", "y7r9": "يحرق", "rasa": "راسه",
    "ta3kom": "تاعكم", "rakom": "راكم", "hta": "حتا",
    "tji": "تجي", "ri7": "ريح", "trou7": "تروح",
    "n9drou": "نقدرو", "nkhlsou": "نخلصو", "nl9a": "نلقا",
    "fibr": "فيبر", "psq": "بسبب", "khir": "خير",
    "balak": "بالاك", "bdlna": "بدلنا", "khalso": "خلصو",
    "draham": "دراهم", "tbgho": "تبغو", "haw": "هاو",
    "3andek": "عندك", "3andi": "عندي",
    "wifi": "واي فاي", "speed": "سرعة", "game": "لعبة",
    "facebook": "فيسبوك", "insta": "انستغرام",
    "youtube": "يوتيوب", "whatsapp": "واتساب",
    "baridimo": "بريدي موب", "baridimob": "بريدي موب",
    "baridicash": "بريدي كاش", "myidoom": "تطبيق idoom", "hty": "حتى",
    "majozch": "ماجازش", "majazch": "ماجازش",
    "masma3nach": "ماسمعناش", "makhdmtouch": "ماخدمتوش",
    "mt9drch": "ما نقدرش", "mt9orch": "ما نقدرش",
    "3lina": "علينا", "3awdoulna": "عاودولنا",
    "s7ab": "الصحاب", "s7abi": "صحابي",
    "nkhdmou": "نخدمو", "nkhdm": "نخدم",
    "kdabin": "كذابين", "kdab": "كذاب",
     "minpa": "مينبا",
    "mn": "من", "fi": "في",
  },
  "arabizi_upper": {
    "INCHALLAH": "إن شاء الله", "INCHALAH": "إن شاء الله",
    "INSHALLAH": "إن شاء الله", "INSHALAH": "إن شاء الله",
    "NCHALH": "إن شاء الله", "WALLAH": "والله", "WALLAHI": "والله",
    "WELLAH": "والله", "WLH": "والله",
    "SLM": "سلام", "SLM,": "سلام", "SLM.": "سلام", "SLM!": "سلام",
    "WACH": "واش", "KHAYBA": "خايبة", "ZWINA": "زينة",
    "KHLAS": "خلاص", "KHLESNA": "خلصنا",
    "RAHO": "راهو", "DABA": "دابا", "DEBA": "دابا",
    "CHHAL": "شحال", "KAMEL": "كامل", "LAZEM": "لازم",
    "KIFECH": "كيفاش", "KIFACH": "كيفاش",
    "BDLNA": "بدلنا", "KHALSO": "خلصو", "DRAHAM": "دراهم",
    "TBGHO": "تبغو", "HAW": "هاو", "CHWALA": "شوالة",
    "RBNII": "ربي", "CNX": "connexion", "RDM": "شبكة",
    "BARIDIMO": "بريدي موب", "BARIDIMOB": "بريدي موب",
    "BARIDICASH": "بريدي كاش", "MYIDOOM": "تطبيق idoom",
    "HTY": "حتى", "MAJOZCH": "ماجازش", "MAJAZCH": "ماجازش",
    "MASMA3NACH": "ماسمعناش", "MAKHDMTOUCH": "ماخدمتوش",
    "MT9DRCH": "ما نقدرش", "MT9ORCH": "ما نقدرش",
    "G33": "غالقين", "MINPA": "مينبا",
    "GAMING": "الألعاب", "GAME": "لعبة",
  },
  "emojis": {
    "❤️": "حب", "🧡": "حب", "💛": "حب", "💚": "حب", "💙": "حب",
    "💜": "حب", "🖤": "حب", "💕": "حب", "💞": "حب", "💓": "حب",
    "💗": "حب", "💖": "حب", "💘": "حب", "💝": "حب", "♥️": "حب",
    "😊": "فرح", "😃": "فرح", "😄": "فرح", "😁": "فرح", "😆": "فرح",
    "😀": "فرح", "🙂": "رضا", "😇": "طيب", "🥰": "حب",
    "😍": "اعجاب شديد", "🤩": "اعجاب", "🎉": "فرح", "🎊": "فرح",
    "🥳": "فرح", "👍": "اعجاب", "🤝": "تعاون", "👌": "تمام",
    "✅": "تمام", "☑️": "تمام", "✔️": "تمام", "💯": "ممتاز",
    "⭐": "ممتاز", "🌟": "ممتاز", "🏆": "ممتاز", "🙏": "شكر",
    "😠": "غضب", "😡": "غضب شديد", "🤬": "غضب", "😤": "غضب",
    "💢": "غضب", "😒": "عدم رضا", "🙄": "عدم رضا", "😑": "حياد سلبي",
    "😐": "حياد", "👎": "عدم رضا", "🚫": "رفض", "❌": "رفض",
    "😞": "حزن", "😔": "حزن", "😢": "حزن", "😭": "حزن شديد",
    "💔": "خيبة امل", "😩": "تعب", "😫": "تعب", "🥺": "رجاء",
    "😓": "خيبة", "🤔": "شك", "😕": "تشويش", "😟": "قلق",
    "😰": "قلق", "😨": "خوف", "😱": "صدمة", "🤷": "لا أعلم",
    "😂": "ضحك", "🤣": "ضحك", "😅": "حرج", "😏": "سخرية",
    "🥲": "حزن", "🤦": "خيبة", "🤦🏻": "خيبة",
    "🤦‍♂️": "خيبة", "🤦‍♀️": "خيبة",
    "📱": "هاتف", "💻": "حاسوب", "📶": "شبكة", "📡": "إشارة",
    "🔋": "بطارية", "💬": "رسالة", "📲": "هاتف", "🌐": "انترنت",
    "⚡": "سرعة", "🔄": "تحديث", "⚙️": "إعدادات", "🛑": "توقف",
    "⚠️": "تحذير", "❗": "تنبيه", "‼️": "تنبيه شديد",
    "🔔": "تنبيه", "📵": "لا شبكة", "🔇": "صامت",
    "👏": "تصفيق", "💐": "تهنئة", "💀": "غضب شديد",
  },
  "mixed_ar_fr_regex": {
    "slm,": "سلام", "slm.": "سلام", "معاكم": "معكم",
     "االتزام": "التزام", "بيس": "شريحة",
     "البونوس": "بونوس","slm!": "سلام",
    "\\bالبونيص\\b": "bonus", "\\bالبونص\\b": "bonus",
    "\\bبونيص\\b": "bonus", "\\bبونص\\b": "bonus",
    "\\bالكونيكسيون\\b": "اتصال", "\\bكوناكسيون\\b": "اتصال",
    "\\bالكونكسيون\\b": "اتصال", "\\bكونكسيون\\b": "اتصال",
    "\\bكنكسيون\\b": "اتصال",
    "\\bفلكسيلي\\b": "فليكسي", "\\bفليكسيلي\\b": "فليكسي",
    "\\bنفليكسي\\b": "فليكسي", "\\bيفليكسي\\b": "فليكسي",
    "\\bانشالله\\b": "إن شاء الله", "\\bانشاالله\\b": "إن شاء الله",
    "\\bنشالله\\b": "إن شاء الله", "\\bنشاالله\\b": "إن شاء الله",
    "\\bانشاء الله\\b": "إن شاء الله",
    "\\bالانترنيت\\b": "الانترنت", "\\bانترنيت\\b": "الانترنت",
    "\\bالانرنت\\b": "الانترنت", "\\bنترنات\\b": "الانترنت",
    "\\bالانترنات\\b": "الانترنت", "\\bانترنات\\b": "الانترنت",
    "\\bالنت\\b": "الانترنت",
    "\\badisal\\b": "ADSL", "\\badisal\\b": "ADSL",
    "\\bاديسال\\b": "ADSL", "\\bاديزال\\b": "ADSL",
    "\\bادسل\\b": "ADSL", "\\bادياسال\\b": "ADSL",
    "\\bالموادم\\b": "المودم", "\\bموادم\\b": "المودم",
    "\\bالمودام\\b": "المودم", "\\bمودام\\b": "مودم",
    "\\bالروتور\\b": "الموجه", "\\bروتور\\b": "الموجه",
    "\\bلافيبر\\b": "fibre optique", "\\bبالفيبر\\b": "fibre optique",
    "\\bوالفيبر\\b": "و fibre optique",
    "\\bاوبتيك\\b": "optique", "\\bاوبتيق\\b": "optique",
    "\\bبينغ\\b": "ping", "\\bالبينغ\\b": "ping",
    "\\bبينج\\b": "ping", "\\bالبينج\\b": "ping",
    "\\bايدوم\\b": "Idoom",
    "\\bجيفا\\b": "جيجا", "\\bجيڤا\\b": "جيجا",
    "\\bميڤا\\b": "ميجا", "\\bميڨا\\b": "ميجا",
    "\\bكريدي\\b": "رصيد",
    "(\\d+[Gg])([\\u0600-\\u06FF])": "\\1 \\2",
    "\\bسيرفر\\b": "serveur", "\\bالسيرفر\\b": "serveur",
    "\\bتيفي بوكس\\b": "TV Box", "\\bتيفيبوكس\\b": "TV Box",
    "\\bتوين بوكس\\b": "Twinbox", "\\bتوينبوكس\\b": "Twinbox",
    "\\bبروموسيون\\b": "promotion", "\\bبروموشن\\b": "promotion",
    "\\bموديم\\b": "مودم", "\\bالموديم\\b": "المودم",
    "\\bولله\\b": "والله", "\\bوالله\\b": "والله",
    "\\bنتفلكس\\b": "Netflix", "\\bنتفليكس\\b": "Netflix",
    "\\bامزون\\b": "Amazon", "\\bأمازون\\b": "Amazon",
    "\\bلاديزال\\b": "ADSL", "\\bلاديسال\\b": "ADSL",
    "\\bفايبر\\b": "fibre optique",
    "\\bويفي\\b": "Wi-Fi", "\\bالويفي\\b": "Wi-Fi",
    "\\bديبي\\b": "débit", "\\bالديبي\\b": "débit",
    "\\bمي بوكس\\b": "Mi Box", "\\bميبوكس\\b": "Mi Box",
    "\\bالفكس\\b": "الخط الثابت", "\\bالفيكس\\b": "الخط الثابت",
    "(?<![a-zA-Z])\\bفيبر\\b(?![a-zA-Z])": "fibre optique",
    "ميقا": "Mo", "جيقا": "Go",
    "\\bnokia\\b": "Nokia", "\\btenda\\b": "Tenda",
    "\\bzte\\b": "ZTE", "\\bhuawei\\b": "Huawei",
    "\\bbaridimo\\b": "بريدي موب", "\\bbaridimob\\b": "بريدي موب",
    "\\bbaridicash\\b": "بريدي كاش",
  },
  "network_variants": {
    "latin": [
      "wrizo","rizo","riso","rysou","resou","risou","rizou",
      "risseau","rézo","rezo","riseau","reseau","rizoo",
      "wriso","wreza","reza","rza","rezou","rezoo",
      "wrisseau","wrisso","rrizou","wrizzo","rizzo","reezo","rizeau"
    ],
    "arabic": [
      "الريزو","ريزو","الرزو","رزو","الريسو","ريسو","الريزا","ريزا"
    ],
    "normalized_form": "شبكة"
  },
  "abbreviations": {
    "bjr": "bonjour", "bonj": "bonjour", "bsr": "bonsoir",
    "slt": "salut", "cc": "coucou",
    "mrc": "merci", "mrci": "merci", "thx": "merci", "tnx": "merci",
    "svp": "s'il vous plaît", "stp": "s'il te plaît",
    "plz": "s'il vous plaît",
    "pk": "pourquoi", "pcq": "parce que", "pq": "pourquoi",
    "pr": "pour", "tt": "tout", "tjrs": "toujours", "tjs": "toujours",
    "qd": "quand", "ms": "mais", "jsp": "je ne sais pas",
    "nn": "non", "ok": "d'accord", "dac": "d'accord", "okey": "d'accord",
    "prv": "الخاص", "pvt": "الخاص", "bla": "بدون",
    "rdm": "réseau", "cnx": "connexion", "conx": "connexion",
    "co": "connexion", "connection": "connexion",
    "debit": "débit", "db": "débit",
    "4g": "4G", "3g": "3G", "wifi": "Wi-Fi", "wify": "Wi-Fi",
    "app": "application", "appli": "application",
    "tel": "téléphone", "num": "numéro",
    "msg": "message", "sms": "message",
    "whats": "WhatsApp", "wts": "WhatsApp",
    "fb": "Facebook", "insta": "Instagram", "yt": "YouTube",
    "abo": "abonnement", "abt": "abonnement", "abon": "abonnement",
    "forf": "forfait", "forfet": "forfait", "forfai": "forfait",
    "bug": "problème", "bugg": "problème", "pb": "problème",
    "prob": "problème", "prb": "problème", "pbl": "problème",
    "coup": "coupure", "cpr": "coupure", "pan": "panne",
    "lent": "lenteur",
    "at": "Algérie Télécom", "idm": "Idoom",
    "djz": "Djezzy", "mob": "Mobilis", "ood": "Ooredoo",
    "instalation": "installation", "idoom": "Idoom",
  },
  "telecom_tech": {
    "QoE": "QoE", "Speedtest": "Speedtest", "Backbone": "Backbone",
    "Throughput": "Throughput", "Routing": "Routing", "Peering": "Peering",
    "CDN": "CDN", "OLT": "OLT", "QoS": "QoS", "Jitter": "Jitter",
    "GPON": "GPON", "reset": "reset", "re-provision": "re-provision",
    "reprovision": "re-provision",
    "wifi": "Wi-Fi", "wify": "Wi-Fi", "wi-fi": "Wi-Fi", "wlan": "Wi-Fi",
    "wimax": "WiMax", "data": "Internet", "datas": "Internet",
    "inet": "Internet", "net": "Internet", "web": "Internet",
    "internet": "Internet",
    "4g": "4G", "3g": "3G", "2g": "2G", "5g": "5G",
    "lte": "4G", "volte": "VoLTE", "vowifi": "VoWiFi",
    "adsl": "ADSL", "vdsl": "VDSL", "dsl": "ADSL",
    "fttb": "FTTB", "ftth": "FTTH", "dns": "DNS",
    "modem": "modem", "routeur": "routeur", "router": "routeur",
    "sim": "carte SIM", "esim": "eSIM", "ont": "ONT",
    "idoom": "Idoom", "idom": "Idoom",
    "my idoom": "my idoom", "my ooredoo": "my ooredoo",
    "my djezzy": "my djezzy", "my mobilis": "my mobilis",
    "mb": "Mo", "mbps": "Mbps", "mbs": "Mbps",
    "gb": "Go", "go": "Go", "mo": "Mo", "ko": "Ko",
    "kbps": "Kbps", "mega": "ميجا",
    "coupure": "coupure", "panne": "panne", "lenteur": "lenteur",
    "deconnexion": "déconnexion", "instable": "instable",
    "الفيير": "الفيبر", "فيير": "الفيبر",
    "فيبر": "fibre optique", "الفيبر": "fibre optique",
    "بينغ": "ping", "البينغ": "ping", "بينج": "ping", "ping": "ping",
    "twinbox": "Twinbox", "twin box": "Twinbox",
    "tv box": "TV Box", "tvbox": "TV Box",
    "fortnite": "Fortnite", "netflix": "Netflix",
    "prime video": "Prime Video", "amazon": "Amazon",
    "serveur": "serveur", "server": "serveur",
    "4k": "4K", "8k": "8K", "2k": "2K",
    "hd": "HD", "fhd": "Full HD", "uhd": "UHD",
    "ram": "RAM", "rom": "ROM", "android": "Android", "ios": "iOS",
    "nokia": "Nokia", "tenda": "Tenda", "zte": "ZTE",
    "huawei": "Huawei", "tp-link": "TP-Link", "xiaomi": "Xiaomi",
    "mi box": "Mi Box", "mibox": "Mi Box",
    "iptv": "IPTV", "ethernet": "Ethernet", "starlink": "Starlink",
    "google tv": "Google TV", "google": "Google",
    "débit": "débit", "debit": "débit",
    "مودام": "مودم", "المودام": "مودم",
    "uploaded": "uploaded",
  },
  "french_corrections_regex": {
    "\\bconexion\\b": "connexion", "\\bconection\\b": "connexion",
    "\\bconnection\\b": "connexion", "\\bconexsion\\b": "connexion",
    "\\bconecter\\b": "connecter", "\\bconnecter\\b": "connecter",
    "\\bdéconecte\\b": "déconnecter",
    "\\bresau\\b": "réseau", "\\breseau\\b": "réseau",
    "\\brésau\\b": "réseau", "\\breseaux\\b": "réseaux",
    "\\bprobleme\\b": "problème", "\\bproblem\\b": "problème",
    "\\bservic\\b": "service", "\\bdebit\\b": "débit",
    "\\babonement\\b": "abonnement", "\\babonnment\\b": "abonnement",
    "\\bforfet\\b": "forfait", "\\bforféit\\b": "forfait",
    "\\bcouppure\\b": "coupure", "\\blanteur\\b": "lenteur",
    "\\brecharg\\b": "recharge", "\\bportable\\b": "téléphone",
    "\\btelephone\\b": "téléphone", "\\baganse\\b": "agence",
    "\\bmeme\\b": "même", "\\binstalation\\b": "installation",
    "\\bsebtembre\\b": "septembre", "\\boctobre\\b": "octobre",
  },
  "units": {
    "mbps": "Mbps", "mb/s": "Mbps", "mbs": "Mbps",
    "gbps": "Gbps", "gb/s": "Gbps",
    "kbps": "Kbps", "kb/s": "Kbps",
    "mb": "Mo", "mo": "Mo", "gb": "Go", "go": "Go", "kb": "Ko",
    "meg": "Mo", "mega": "Mo", "gig": "Go", "giga": "Go",
    "ms": "ms", "mn": "min", "min": "min",
    "heure": "h", "heures": "h",
    "da": "DA", "dinar": "DA", "dinars": "DA",
    "4k": "4K", "8k": "8K", "2k": "2K",
  }
}

DICT_STOP = {
  "negations": {
    "arabe_standard": ["ما","لا","لم","لن","ليس","غير","لات","إلا"],
    "dialecte_algerien": ["مكانش","ماكش","ماهيش","ماهوش","مش","ميش","ماشي","مانيش"]
  },
  "dialect_keep": {
    "questions": ["واش","كيفاش","وين","علاش","قديش","فاش","منين","شحال"],
    "etat_situation": ["راه","راهي","راني","راك","راهم","راهو","مزال","ديما","درك"],
    "connecteurs": ["كيما","باه","حتى","بصح","غير","ولو"],
    "pronoms": ["أنا","أنت","أنتم","نحن","هما","نتا","نتي","نتوما","حنا","هوما"],
    "prepositions": ["من","لي","في","على","بعد","نفس","كل","منذ","عند","بين","تاع","ديال","إلى","عن","مع"],
    "francais_garde": ["ya","pas","de","en","avec","depuis","pour","par","sur","sous","dans",
                       "entre","sans","vers","bien","tout","même","autre","alors","comme",
                       "quand","où","après","avant","pendant","très","plus","moins","aussi",
                       "au","aux","tous","toute","toutes","on","si","ne","mais"],
    "commandes": ["reset","re-provision","reprovision"],
    "negations_composees": ["ماجازش","ماسمعناش","ماخدمتوش","ما نقدرش","مايمشيش","مكانش"],
  },
  "protected_words": {
    "termes_fr_gardes": ["connexion","problème","réseau","service","débit","coupure","panne",
                         "bonjour","merci","solution","compte","même","comme","vraiment","mois"],
    "termes_techniques": ["QoE","Speedtest","Traffic Shaping","Backbone","Throughput","Routing",
                          "Peering","CDN","OLT","QoS","Jitter","Core Network","GPON","reset"],
    "reseaux_sociaux": ["facebook","whatsapp","youtube","instagram","tiktok","twitter"],
    "apps_algerie": ["aadl","baridimob","baridicash","ccp","idoom","my idoom","my ooredoo",
                     "my djezzy","my mobilis","myidoom"],
  }
}
